# Generated by Django 3.0.4 on 2020-04-17 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(default='', help_text='한글로 입력해주세요. ex)上单/中路', max_length=20, verbose_name='라인')),
                ('keyword', models.CharField(default='', help_text='"/" 로 구분해주세요. ex)가렌/garen', max_length=255, verbose_name='검색어')),
                ('no', models.CharField(default='', max_length=3, verbose_name='角色번호')),
                ('name', models.CharField(default='', help_text='한글로 입력해주세요. ex)가렌', max_length=20, verbose_name='角色명')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=255, verbose_name='매치 이름')),
                ('red_team_name', models.CharField(max_length=255, verbose_name='红队名称')),
                ('blue_team_name', models.CharField(max_length=255, verbose_name='蓝队名称')),
                ('password', models.CharField(max_length=255, verbose_name='패스워드')),
                ('banpick', models.CharField(blank=True, max_length=255, verbose_name='禁选Data')),
                ('timer', models.DateTimeField(blank=True, null=True, verbose_name='시작')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='일시')),
            ],
            options={
                'verbose_name': '禁选',
                'verbose_name_plural': '禁选',
            },
        ),
    ]
